/**
 * Canonical map: GICS/TradingView sector → ธาตุไทย
 *
 * รวม SECTOR_TO_ELEMENT (fetch-wikipedia-stocks.ts) + TV_SECTOR_TO_ELEMENT (expand-to-100.ts)
 * ไว้ที่เดียว — ใช้กับ IPO / hidden gems / assets / movers
 * (สคริปต์เดิมยังใช้ map ของตัวเอง — ค่อย refactor ทีหลัง)
 */
import type { ThaiElement } from "../investor/stock-database";

const GICS_TO_ELEMENT: Record<string, ThaiElement> = {
  Technology: "ทอง",
  "Information Technology": "ทอง",
  Semiconductors: "ทอง",
  "Communication Services": "ไม้",
  "Telecommunication Services": "ไม้",
  Financials: "น้ำ",
  Banks: "น้ำ",
  Insurance: "น้ำ",
  "Financial Services": "น้ำ",
  "Capital Markets": "น้ำ",
  Energy: "ไฟ",
  Utilities: "ไฟ",
  "Electric Utilities": "ไฟ",
  "Health Care": "ไฟ",
  Pharmaceuticals: "ไฟ",
  Biotechnology: "ไฟ",
  "Health Care Equipment & Services": "ไฟ",
  "Consumer Discretionary": "น้ำ",
  "Consumer Staples": "น้ำ",
  "Food & Beverage": "น้ำ",
  "Food and Beverage": "น้ำ",
  Retailing: "น้ำ",
  "Consumer Products": "น้ำ",
  "Household & Personal Products": "น้ำ",
  Materials: "ทอง",
  "Metals & Mining": "ทอง",
  Chemicals: "ทอง",
  "Paper & Forest Products": "ไม้",
  Industrials: "ทอง",
  "Capital Goods": "ทอง",
  Machinery: "ทอง",
  "Automobiles & Components": "ทอง",
  "Auto & Truck Manufacturers": "ทอง",
  Transportation: "น้ำ",
  Airlines: "น้ำ",
  Railroads: "น้ำ",
  "Real Estate": "ดิน",
  "Real Estate Investment Trusts": "ดิน",
  Construction: "ดิน",
  "Engineering & Construction": "ดิน",
  "Basic Materials": "ทอง",
  Conglomerates: "น้ำ",
  "Diversified Financials": "น้ำ",
  Software: "ทอง",
  Hardware: "ทอง",
  "Media & Entertainment": "น้ำ",
  Media: "ไม้",
  "Hotels, Restaurants & Leisure": "น้ำ",
  "Aerospace & Defense": "ทอง",
  "Food & Staples Retailing": "น้ำ",
  "GIC Sector": "น้ำ", // fallback header
};

/** TradingView taxonomy (ต่างจาก GICS เล็กน้อย) */
const TV_TO_ELEMENT: Record<string, ThaiElement> = {
  "Technology Services": "ทอง",
  "Electronic Technology": "ทอง",
  "Producer Manufacturing": "ทอง",
  "Process Industries": "ทอง",
  "Energy Minerals": "ไฟ",
  "Non-Energy Minerals": "ทอง",
  "Health Technology": "ไฟ",
  "Health Services": "ไฟ",
  "Finance": "น้ำ",
  "Major Banks": "น้ำ",
  "Regional Banks": "น้ำ",
  "Savings Banks": "น้ำ",
  "Insurance": "น้ำ",
  "Investment Banks/Brokers": "น้ำ",
  "Finance/Rental/Leasing": "น้ำ",
  "Consumer Non-Durables": "น้ำ",
  "Consumer Durables": "น้ำ",
  "Retail Trade": "น้ำ",
  "Food: Major Diversified": "น้ำ",
  "Food: Specialty/Candy": "น้ำ",
  "Beverages: Alcoholic": "น้ำ",
  "Beverages: Non-Alcoholic": "น้ำ",
  "Food Retail": "น้ำ",
  "Drugstore Chains": "น้ำ",
  "Apparel/Footwear": "น้ำ",
  "Textiles": "น้ำ",
  "Utilities": "ไฟ",
  "Electric Utilities": "ไฟ",
  "Gas Distributors": "ไฟ",
  "Water Utilities": "น้ำ",
  "Transportation": "น้ำ",
  "Air Freight/Trucking": "น้ำ",
  "Railroads": "น้ำ",
  "Marine Shipping": "น้ำ",
  "Airlines": "น้ำ",
  "Industrial Services": "ทอง",
  "Commercial Services": "น้ำ",
  "Distribution Services": "น้ำ",
  "Real Estate": "ดิน",
  "Real Estate Investment Trusts": "ดิน",
  "Real Estate Development": "ดิน",
  "Homebuilding": "ดิน",
  "Construction Materials": "ดิน",
  "Engineering & Construction": "ดิน",
  "Miscellaneous": "น้ำ",
  "Packaged Software": "ทอง",
  "Semiconductors": "ทอง",
  "Computer Processing Hardware": "ทอง",
  "Electronic Equipment/Instruments": "ทอง",
  "Electrical Products": "ทอง",
  "Aerospace & Defense": "ทอง",
  "Motor Vehicles": "ทอง",
  "Auto Parts: OEM": "ทอง",
  "Trucks/Construction/Farm Machinery": "ทอง",
  "Industrial Machinery": "ทอง",
  "Metal Fabrication": "ทอง",
  "Precious Metals": "ทอง",
  "Aluminum": "ทอง",
  "Steel": "ทอง",
  "Coal": "ไฟ",
  "Oil & Gas Production": "ไฟ",
  "Oil & Gas Transportation": "ไฟ",
  "Oil Refining/Marketing": "ไฟ",
  "Chemicals: Major Diversified": "ทอง",
  "Chemicals: Specialty": "ทอง",
  "Agricultural Commodities/Milling": "ไม้",
  "Forest Products": "ไม้",
  "Pharmaceuticals: Major": "ไฟ",
  "Pharmaceuticals: Other": "ไฟ",
  "Medical Specialties": "ไฟ",
  "Medical Instruments": "ไฟ",
  "Biotechnology": "ไฟ",
  "Healthcare": "ไฟ",
  "Realty": "ดิน",
};

/** ค้น sector → ธาตุ (GICS ก่อน แล้ว TradingView) — ไม่รู้จัก → null (ไม่เดา) */
export function sectorToElement(sector: string | null | undefined): ThaiElement | null {
  if (!sector) return null;
  const s = sector.trim();
  return GICS_TO_ELEMENT[s] ?? TV_TO_ELEMENT[s] ?? null;
}
